### ISSUE TITLE
Is this project mantained?

### ISSUE THREAD

**Issue by 0m15** [mozilla/node-client-sessions#106]
Please give some details about the topic, as it seems that the library is completely broken on latest Express version (4.3.13), also as reported on #105

**Comment by ponelat** [comment]
seems to be working on my setup... `express@4.13.3` what exactly is your issue?

**Comment by Mithgol** [comment]
This module also works for me on Express.js version 4.13.1 (which is not exactly 4.13.3, but [the differences](https://github.com/strongloop/express/compare/4.13.1...4.13.3) are minimal and shouldn't affect sessions).

However, I don't use Passport as in #105; I just do the following:

```js
app.use(sessions({
   cookieName: 'XXXXX', // the key name added to the request object
   secret: 'YYYYYYYYYYYYYYYY', // a large unguessable string
   duration: 1000 * 60 * 60 * 10, // 10hr: how long a session stays valid
   activeDuration: 1000 * 60 * 15 // 15min: if expiresIn < activeDuration,
                                // a session is extended by activeDuration
}));
```

(of course, some real values are used instead of `XXX` and `YYY` but they should stay secret).

**Comment by atnmorrison** [comment]
I'm also wondering if I should look for something else, it doesn't look like the source code has been touched for several years other than updating the readme, and it's still at version 0.7 has it been abandoned?

**Comment by seanmonstar** [comment]
We don't spend much time actively working on this library, but that's in part because it does all we need. We used it extensively in Persona, but use a different authentication strategy entirely in Firefox Accounts. Not because this is bad, but we just had different needs. The minor services we have that still use this haven't had a need for changes, so we haven't made changes.

If there is a bug, a PR is always welcome!
